# Generated by Django 4.2.5 on 2023-09-07 14:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Prospect',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField()),
                ('industry', models.CharField()),
                ('history', models.CharField()),
                ('mission', models.CharField()),
                ('core_values', models.CharField()),
                ('solutions_offered', models.CharField()),
                ('client_testimonials', models.CharField()),
                ('value_proposition', models.CharField()),
            ],
        ),
        migrations.CreateModel(
            name='JobDescription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('job_title', models.CharField(max_length=255)),
                ('job_summary', models.TextField()),
                ('responsibilities', models.TextField()),
                ('preferred_qualifications', models.TextField(blank=True, null=True)),
                ('company_overview', models.TextField()),
                ('location', models.CharField(max_length=255)),
                ('team_name', models.CharField()),
                ('technology_stack', models.CharField()),
                ('prospect', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sea.prospect')),
            ],
        ),
        migrations.CreateModel(
            name='Email',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField()),
                ('body', models.CharField(max_length=1000)),
                ('prospect', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sea.prospect')),
            ],
        ),
    ]
