# Generated by Django 4.2.5 on 2023-09-10 08:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sea', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='email',
            name='jd',
            field=models.OneToOneField(default=None, on_delete=django.db.models.deletion.CASCADE, to='sea.jobdescription'),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='BackgroundJob',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.BooleanField()),
                ('email', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='sea.email')),
                ('prospect', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sea.prospect')),
            ],
        ),
    ]
