# Generated by Django 4.2.5 on 2023-09-10 08:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sea', '0002_email_jd_backgroundjob'),
    ]

    operations = [
        migrations.RenameField(
            model_name='email',
            old_name='jd',
            new_name='job_description',
        ),
        migrations.AlterField(
            model_name='email',
            name='body',
            field=models.TextField(max_length=1000),
        ),
        migrations.AlterField(
            model_name='email',
            name='subject',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='jobdescription',
            name='location',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='jobdescription',
            name='team_name',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='jobdescription',
            name='technology_stack',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='prospect',
            name='client_testimonials',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='prospect',
            name='core_values',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='prospect',
            name='history',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='prospect',
            name='industry',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='prospect',
            name='mission',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='prospect',
            name='name',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='prospect',
            name='solutions_offered',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='prospect',
            name='value_proposition',
            field=models.TextField(),
        ),
    ]
