# Generated by Django 4.2.5 on 2023-09-10 12:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sea', '0004_backgroundjob_created_at_backgroundjob_created_by_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='prospect',
            name='website',
            field=models.URLField(default=None),
            preserve_default=False,
        ),
    ]
