# Generated by Django 4.2.5 on 2023-09-10 13:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sea', '0005_prospect_website'),
    ]

    operations = [
        migrations.AddField(
            model_name='email',
            name='type',
            field=models.CharField(choices=[('introductory', 'Introductory')], default='introductory', max_length=20),
        ),
    ]
