# Generated by Django 4.2.5 on 2023-09-10 13:41

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('sea', '0007_jobdescription_raw'),
    ]

    operations = [
        migrations.AlterField(
            model_name='backgroundjob',
            name='created_at',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='backgroundjob',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created_by', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='backgroundjob',
            name='email',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to='sea.email'),
        ),
        migrations.AlterField(
            model_name='backgroundjob',
            name='prospect',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='sea.prospect'),
        ),
        migrations.AlterField(
            model_name='backgroundjob',
            name='updated_at',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='backgroundjob',
            name='updated_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_updated_by', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='email',
            name='created_at',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='email',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created_by', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='email',
            name='job_description',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to='sea.jobdescription'),
        ),
        migrations.AlterField(
            model_name='email',
            name='prospect',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='sea.prospect'),
        ),
        migrations.AlterField(
            model_name='email',
            name='updated_at',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='email',
            name='updated_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_updated_by', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='jobdescription',
            name='created_at',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='jobdescription',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created_by', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='jobdescription',
            name='location',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='jobdescription',
            name='preferred_qualifications',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='jobdescription',
            name='prospect',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='sea.prospect'),
        ),
        migrations.AlterField(
            model_name='jobdescription',
            name='updated_at',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='jobdescription',
            name='updated_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_updated_by', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='prospect',
            name='created_at',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='prospect',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created_by', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='prospect',
            name='updated_at',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='prospect',
            name='updated_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_updated_by', to=settings.AUTH_USER_MODEL),
        ),
    ]
