# Generated by Django 4.2.5 on 2023-09-10 16:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sea', '0009_alter_backgroundjob_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='backgroundjob',
            name='celery_job_id',
            field=models.CharField(default=None),
            preserve_default=False,
        ),
    ]
