# Generated by Django 4.2.5 on 2023-09-10 16:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sea', '0011_alter_backgroundjob_celery_job_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='backgroundjob',
            old_name='celery_job_id',
            new_name='celery_task_id',
        ),
    ]
