# Generated by Django 4.2.5 on 2023-09-10 16:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sea', '0012_rename_celery_job_id_backgroundjob_celery_task_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='backgroundjob',
            name='celery_task_id',
            field=models.CharField(),
        ),
    ]
